// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:08 2021
// </auto-generated>
// --------------------------------------------------

import { GenerateShim } from "../../Foundation/Interop/GenerateShim";
import { EdgeGestureKind } from "./EdgeGestureKind";

@GenerateShim('Windows.UI.Input.EdgeGestureEventArgs')
export class EdgeGestureEventArgs { 
    kind: EdgeGestureKind = null;
}
