packages:
  - 'src/server'
  - 'src/shared'
  - 'src/shell'
  - 'src/config'
  - 'src/apps/*'
  - 'tools/manifest-loader'
  - 'tools/xml-loader'

# enable inject-workspace-packages
# https://pnpm.io/workspaces#monorepo-features
injectWorkspacePackages: true