//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:v8.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import './index.scss'

import {
    TileSquare150x150PeekImageAndText01,
    TileSquare150x150PeekImageAndText02,
    TileSquare150x150PeekImageAndText03,
    TileSquare150x150PeekImageAndText04
} from './TileSquare150x150PeekImageAndText'
import {
    TileSquare150x150Text01,
    TileSquare150x150Text02,
    TileSquare150x150Text03,
    TileSquare150x150Text04
} from './TileSquare150x150Text'
import {
    TileSquare310x310BlockAndText01,
    TileSquare310x310BlockAndText02
} from './TileSquare310x310BlockAndText'
import {
    TileSquare310x310ImageAndText01,
    TileSquare310x310ImageAndText02
} from './TileSquare310x310ImageAndText'
import {
    TileSquare310x310ImageAndTextOverlay01,
    TileSquare310x310ImageAndTextOverlay02,
    TileSquare310x310ImageAndTextOverlay03
} from './TileSquare310x310ImageAndTextOverlay'
import {
    TileSquare310x310ImageCollectionAndText01,
    TileSquare310x310ImageCollectionAndText02
} from './TileSquare310x310ImageCollectionAndText'
import {
    TileSquare310x310SmallImagesAndTextList01,
    TileSquare310x310SmallImagesAndTextList02,
    TileSquare310x310SmallImagesAndTextList03,
    TileSquare310x310SmallImagesAndTextList04,
    TileSquare310x310SmallImagesAndTextList05
} from './TileSquare310x310SmallImagesAndTextList'
import {
    TileSquare310x310Text01,
    TileSquare310x310Text02,
    TileSquare310x310Text03,
    TileSquare310x310Text04,
    TileSquare310x310Text05,
    TileSquare310x310Text06,
    TileSquare310x310Text07,
    TileSquare310x310Text08,
    TileSquare310x310Text09
} from './TileSquare310x310Text'
import {
    TileSquare310x310TextList01,
    TileSquare310x310TextList02,
    TileSquare310x310TextList03
} from './TileSquare310x310TextList'
import {
    TileWide310x150BlockAndText01,
    TileWide310x150BlockAndText02
} from './TileWide310x150BlockAndText'
import {
    TileWide310x150ImageAndText01,
    TileWide310x150ImageAndText02
} from './TileWide310x150ImageAndText'
import {
    TileWide310x150PeekImage01,
    TileWide310x150PeekImage02,
    TileWide310x150PeekImage03,
    TileWide310x150PeekImage04,
    TileWide310x150PeekImage05,
    TileWide310x150PeekImage06,
    TileWide310x150PeekImage07
} from './TileWide310x150PeekImage'
import {
    TileWide310x150PeekImageAndText01,
    TileWide310x150PeekImageAndText02
} from './TileWide310x150PeekImageAndText'
import {
    TileWide310x150PeekImageCollection01,
    TileWide310x150PeekImageCollection02,
    TileWide310x150PeekImageCollection03,
    TileWide310x150PeekImageCollection04,
    TileWide310x150PeekImageCollection05,
    TileWide310x150PeekImageCollection06
} from './TileWide310x150PeekImageCollection'
import {
    TileWide310x150SmallImageAndText01,
    TileWide310x150SmallImageAndText02,
    TileWide310x150SmallImageAndText03,
    TileWide310x150SmallImageAndText04,
    TileWide310x150SmallImageAndText05
} from './TileWide310x150SmallImageAndText'
import {
    TileWide310x150Text01,
    TileWide310x150Text02,
    TileWide310x150Text03,
    TileWide310x150Text04,
    TileWide310x150Text05,
    TileWide310x150Text06,
    TileWide310x150Text07,
    TileWide310x150Text08,
    TileWide310x150Text09,
    TileWide310x150Text10,
    TileWide310x150Text11
} from './TileWide310x150Text'

import TileSquare150x150Block from './TileSquare150x150Block'
import TileSquare150x150Image from './TileSquare150x150Image'
import TileSquare310x310Image from './TileSquare310x310Image'
import TileSquare310x310ImageCollection from './TileSquare310x310ImageCollection'
import TileSquare310x310NoAssetFallback from './TileSquare310x310NoAssetFallback'
import TileSquare310x310SmallImageAndText01 from './TileSquare310x310SmallImageAndText01'
import TileSquare70x70Image from './TileSquare70x70Image'
import TileWide310x150Image from './TileWide310x150Image'
import TileWide310x150ImageCollection from './TileWide310x150ImageCollection'

const TileTemplates = {
    TileSquare150x150Block,
    TileSquare150x150Image,
    TileSquare150x150PeekImageAndText01,
    TileSquare150x150PeekImageAndText02,
    TileSquare150x150PeekImageAndText03,
    TileSquare150x150PeekImageAndText04,
    TileSquare150x150Text01,
    TileSquare150x150Text02,
    TileSquare150x150Text03,
    TileSquare150x150Text04,
    TileSquare310x310BlockAndText01,
    TileSquare310x310BlockAndText02,
    TileSquare310x310Image,
    TileSquare310x310ImageAndText01,
    TileSquare310x310ImageAndText02,
    TileSquare310x310ImageAndTextOverlay01,
    TileSquare310x310ImageAndTextOverlay02,
    TileSquare310x310ImageAndTextOverlay03,
    TileSquare310x310ImageCollection,
    TileSquare310x310ImageCollectionAndText01,
    TileSquare310x310ImageCollectionAndText02,
    TileSquare310x310NoAssetFallback,
    TileSquare310x310SmallImageAndText01,
    TileSquare310x310SmallImagesAndTextList01,
    TileSquare310x310SmallImagesAndTextList02,
    TileSquare310x310SmallImagesAndTextList03,
    TileSquare310x310SmallImagesAndTextList04,
    TileSquare310x310SmallImagesAndTextList05,
    TileSquare310x310Text01,
    TileSquare310x310Text02,
    TileSquare310x310Text03,
    TileSquare310x310Text04,
    TileSquare310x310Text05,
    TileSquare310x310Text06,
    TileSquare310x310Text07,
    TileSquare310x310Text08,
    TileSquare310x310Text09,
    TileSquare310x310TextList01,
    TileSquare310x310TextList02,
    TileSquare310x310TextList03,
    TileSquare70x70Image,
    TileWide310x150BlockAndText01,
    TileWide310x150BlockAndText02,
    TileWide310x150Image,
    TileWide310x150ImageAndText01,
    TileWide310x150ImageAndText02,
    TileWide310x150ImageCollection,
    TileWide310x150PeekImage01,
    TileWide310x150PeekImage02,
    TileWide310x150PeekImage03,
    TileWide310x150PeekImage04,
    TileWide310x150PeekImage05,
    TileWide310x150PeekImage06,
    TileWide310x150PeekImage07,
    TileWide310x150PeekImageAndText01,
    TileWide310x150PeekImageAndText02,
    TileWide310x150PeekImageCollection01,
    TileWide310x150PeekImageCollection02,
    TileWide310x150PeekImageCollection03,
    TileWide310x150PeekImageCollection04,
    TileWide310x150PeekImageCollection05,
    TileWide310x150PeekImageCollection06,
    TileWide310x150SmallImageAndText01,
    TileWide310x150SmallImageAndText02,
    TileWide310x150SmallImageAndText03,
    TileWide310x150SmallImageAndText04,
    TileWide310x150SmallImageAndText05,
    TileWide310x150Text01,
    TileWide310x150Text02,
    TileWide310x150Text03,
    TileWide310x150Text04,
    TileWide310x150Text05,
    TileWide310x150Text06,
    TileWide310x150Text07,
    TileWide310x150Text08,
    TileWide310x150Text09,
    TileWide310x150Text10,
    TileWide310x150Text11
}

export default TileTemplates
