//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:v8.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import TileWide310x150BlockAndText01 from './TileWide310x150BlockAndText01'
import TileWide310x150BlockAndText02 from './TileWide310x150BlockAndText02'

export {
    TileWide310x150BlockAndText01,
    TileWide310x150BlockAndText02,
};
