//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:v8.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import "./tile-square310x310-text06.scss"
import TileTemplateProps from '../TileTemplateProps'
import TileNotificationBinding from '../TileNotificationBinding'
import TileImageBinding from '../TileImageBinding'
import TileTextBinding from '../TileTextBinding'

export default function TileSquare310x310Text06(props: TileTemplateProps) {
    const text1 = props.elements.find(b => b.id === 1 && b.type === 'text');
    const text2 = props.elements.find(b => b.id === 2 && b.type === 'text');
    const text3 = props.elements.find(b => b.id === 3 && b.type === 'text');
    const text4 = props.elements.find(b => b.id === 4 && b.type === 'text');
    const text5 = props.elements.find(b => b.id === 5 && b.type === 'text');
    const text6 = props.elements.find(b => b.id === 6 && b.type === 'text');
    const text7 = props.elements.find(b => b.id === 7 && b.type === 'text');
    const text8 = props.elements.find(b => b.id === 8 && b.type === 'text');
    const text9 = props.elements.find(b => b.id === 9 && b.type === 'text');
    const text10 = props.elements.find(b => b.id === 10 && b.type === 'text');
    const text11 = props.elements.find(b => b.id === 11 && b.type === 'text');
    const text12 = props.elements.find(b => b.id === 12 && b.type === 'text');
    const text13 = props.elements.find(b => b.id === 13 && b.type === 'text');
    const text14 = props.elements.find(b => b.id === 14 && b.type === 'text');
    const text15 = props.elements.find(b => b.id === 15 && b.type === 'text');
    const text16 = props.elements.find(b => b.id === 16 && b.type === 'text');
    const text17 = props.elements.find(b => b.id === 17 && b.type === 'text');
    const text18 = props.elements.find(b => b.id === 18 && b.type === 'text');
    const text19 = props.elements.find(b => b.id === 19 && b.type === 'text');
    const text20 = props.elements.find(b => b.id === 20 && b.type === 'text');
    const text21 = props.elements.find(b => b.id === 21 && b.type === 'text');
    const text22 = props.elements.find(b => b.id === 22 && b.type === 'text');
    
    return (
        <TileNotificationBinding className="tile-square310x310-text06" forceBadgePlate={true} dynamicFormat={false} x={0} y={0} width={248} height={248}>
            <div className="images" />
            <div className="text-fields">
                <TileTextBinding className="tile-body-text-style id-1" binding={text1} />
                <TileTextBinding className="tile-body-text-style id-2" binding={text2} />
                <TileTextBinding className="tile-body-text-style id-3" binding={text3} />
                <TileTextBinding className="tile-body-text-style id-4" binding={text4} />
                <TileTextBinding className="tile-body-text-style id-5" binding={text5} />
                <TileTextBinding className="tile-body-text-style id-6" binding={text6} />
                <TileTextBinding className="tile-body-text-style id-7" binding={text7} />
                <TileTextBinding className="tile-body-text-style id-8" binding={text8} />
                <TileTextBinding className="tile-body-text-style id-9" binding={text9} />
                <TileTextBinding className="tile-body-text-style id-10" binding={text10} />
                <TileTextBinding className="tile-body-text-style id-11" binding={text11} />
                <TileTextBinding className="tile-body-text-style id-12" binding={text12} />
                <TileTextBinding className="tile-body-text-style id-13" binding={text13} />
                <TileTextBinding className="tile-body-text-style id-14" binding={text14} />
                <TileTextBinding className="tile-body-text-style id-15" binding={text15} />
                <TileTextBinding className="tile-body-text-style id-16" binding={text16} />
                <TileTextBinding className="tile-body-text-style id-17" binding={text17} />
                <TileTextBinding className="tile-body-text-style id-18" binding={text18} />
                <TileTextBinding className="tile-body-text-style id-19" binding={text19} />
                <TileTextBinding className="tile-body-text-style id-20" binding={text20} />
                <TileTextBinding className="tile-body-text-style id-21" binding={text21} />
                <TileTextBinding className="tile-body-text-style id-22" binding={text22} />
            </div>
        </TileNotificationBinding>
    );
}
