// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:09 2021
// </auto-generated>
// --------------------------------------------------

enum ViewSizePreference {
    default,
    useLess,
    useHalf,
    useMore,
    useMinimum,
    useNone,
}

export default ViewSizePreference;